version: '3.8'

services:
  frontend:
    build:
      context: ./cpr-trainer-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./cpr-trainer-frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
    platform: linux/amd64

  backend:
    build:
      context: ./cpr-trainer-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - frontend
    platform: linux/amd64